### ISSUE TITLE
Linux build instructions leave out the ..

### ISSUE THREAD

**Issue by goatchurchprime** [arobenko/cc.ublox.commsdsl#1]
Third line in the linux instructions should read:

`$> cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/install ..`

(The command is correct for the Windows instructions)

**Comment by arobenko** [comment]
Thanks. It looks like README files of my other projects have the same problem of missing "..". I'll fix it in my next release.

**Comment by arobenko** [comment]
Fixed
