### ISSUE TITLE
WSL support

### ISSUE THREAD

**Issue by andreamancuso** [arobenko/cc.ublox.commsdsl#10]
Hi @arobenko 

I followed [these instructions](https://github.com/commschamp/cc.ublox.commsdsl?tab=readme-ov-file#linux-build) on my Ubuntu 22.04.03 (LTS) WSL instance.

These are the options:

```
option (UBLOX_NO_WARN_AS_ERR "Don't treat compilation warnings as errors." OFF)
option (UBLOX_USE_CCACHE "Use ccache." OFF)
option (UBLOX_GEN_PROTOCOL "Use commsdsl2comms to generate protocol definition" ON)
option (UBLOX_BUILD_PROTOCOL "Build and install protocol definition generated by the commsdsl2comms" ${UBLOX_GEN_PROTOCOL})
option (UBLOX_BUILD_PROT_DOC "Build documentation for generated protocol" ON)
option (UBLOX_GEN_TEST "Use commsdsl2test to generate test project." OFF)
option (UBLOX_BUILD_TEST "Build and install project generated by the commsdsl2test." ${UBLOX_GEN_TEST})
option (UBLOX_GEN_TOOLS "Use commsdsl2tools_qt to generate cc_tools_qt plugin project." OFF)
option (UBLOX_BUILD_TOOLS "Build and install project generated by the commsdsl2tools_qt." ${UBLOX_GEN_TOOLS})
option (UBLOX_GEN_SWIG "Use commsdsl2swig to generate swig bindings project." ON)
option (UBLOX_BUILD_SWIG "Build and install project generated by the commsdsl2swig." ${UBLOX_GEN_SWIG})
option (UBLOX_GEN_EMSCRIPTEN "Use commsdsl2emscripten to generate emscripten bindings project." OFF)
option (UBLOX_BUILD_EMSCRIPTEN "Build and install project generated by the commsdsl2emscripten." ${UBLOX_GEN_EMSCRIPTEN})
option (UBLOX_BUILD_EXAMPLES "Build examples." ON)
```

I ran `make install` and the process seems to be stuck on:

![image](https://github.com/user-attachments/assets/90ce00c7-2173-4af9-9952-6861b010a822)

I tried on 2 laptops (both using WSL).

Thoughts?

Thanks!

**Comment by arobenko** [comment]
Looks like you're stuck on doxygen documentation generation for the generated protocol headers. It has nothing to do with WSL. The full UBX protocol is huge and doxygen just cannot handle it. If left uninterrupted it may finish after several hours (or even days). 

You can try one of the following:
- Disable doxygen documentation generation passing `-DUBLOX_BUILD_PROT_DOC=OFF` to your CMake.
- Use latest release of this project where the `UBLOX_BUILD_PROT_DOC` option is already disabled by default
- Use [cc.ublox.generated](https://github.com/commschamp/cc.ublox.generated) project instead where the protocol definition library is already generated for you from this one.

**Comment by andreamancuso** [comment]
Thanks for the prompt reply!
