### ISSUE TITLE
UBX-NAV-PVT has changed for the zed-f9p

### ISSUE THREAD

**Issue by karmicthreat** [arobenko/cc.ublox.commsdsl#3]
The existing u8 version has a different length so a u9 version will be needed.
<img width="715" alt="Screen Shot 2019-06-04 at 11 26 19 PM" src="https://user-images.githubusercontent.com/1076367/58928390-536f0a00-8720-11e9-91dd-c298fdfcd9f5.png">

**Comment by arobenko** [comment]
Thanks for the report.
I'm a bit busy at this moment and do not plan to dive into supporting ublox-9 in the near future (next couple of months or so).
Please feel free to clone the project, update DSL file(s), should not be difficult to do.
I'll be happy if you submit a pull-request with full support of u-blox 9 messages.

**Comment by jowoeber** [comment]
Hi, 
thanks for this great project.
is the f9p support currently being worked on?
Might I be able to help if so?

**Comment by arobenko** [comment]
Hi @jowoeber,
At this moment my hands are full with development of next version of [COMMS Library](https://github.com/arobenko/comms_champion#comms-library) as well as [commsdsl2comms](https://github.com/arobenko/commsdsl) code generator. Please feel free to update schema files to support ublox-9 devices (should be relatively easy to do) as well and submit your pull request(s). Also please provide a link to the relevant spec when submitting it.

**Comment by arobenko** [comment]
It looks like the definition created for ublox-8 ([NavPvt_u8](https://github.com/commschamp/cc.ublox.commsdsl/blob/master/dsl/message/NavPvt.xml#L62)) is suitable for ublox-9 as well. The generated code resides at [include/ublox/message/NavPvt_u8.h](https://github.com/commschamp/cc.ublox.generated/blob/v0.20/include/ublox/message/NavPvt_u8.h)
