### ISSUE TITLE
F9P Support

### ISSUE THREAD

**Issue by jowoeber** [arobenko/cc.ublox.commsdsl#4]
@arobenko 
Hi,
I tried adding the new ConfigItems as described in the [interface definition](https://www.u-blox.com/sites/default/files/u-blox_ZED-F9P_InterfaceDescription_%28UBX-18010854%29.pdf) but now I dont know how to make the different configuration items. I currently add them just as data but ideally I would like to define items for each item where the key is fixed and the data is constrained to the allowed values. What would be the most elegant way to do this via dsl?

[https://github.com/jowoeber/cc.ublox.commsdsl](https://github.com/jowoeber/cc.ublox.commsdsl)

**Comment by arobenko** [comment]
Hi @jowoeber,
I've taken a quick look at the spec, and if I understand it correctly, the [variant](https://arobenko.gitbooks.io/commsdsl-specification/content/fields/variant.html) fields was designed for such heterogeneous lists.

The spec indicates that every key is unique (although splits it into multiple sub-fields). I'd recommend using 32bit integers with raw hex values as they appear in the spec. It is possible to split the key using 
[bitfields](https://arobenko.gitbooks.io/commsdsl-specification/content/fields/bitfield.html), but the read/write performance will suffer. 

You can use properties list of [mqtt5](https://github.com/arobenko/cc.mqtt5.commsdsl/blob/master/dsl/schema.xml#L56) as reference. See also [Heterogeneous Lists](https://arobenko.github.io/cc/tutorials/2019/06/08/heterogeneous-lists/) article for guidance.

Also note that today I've created new release v0.8 of this project, which uses v2.1 of commsdsl code generator. It generates `switch` statement based "read()" and "currFieldExec()" member functions for such variant fields, which are expected to give better runtime performance than default functionality provided by the **COMMS** library.

Hope it helps.

**Comment by arobenko** [comment]
Full support of ublox-9 receiver was introduced in the recent [v0.20](https://github.com/commschamp/cc.ublox.commsdsl/releases/tag/v0.20) release.
