### ISSUE TITLE
Setting Configuration for CfgTp5 

### ISSUE THREAD

**Issue by v-prgmr** [arobenko/cc.ublox.commsdsl#5]
Greetings,

How do I set values for the fields under the struct CfgTp5Fields? 

Thank You

**Comment by arobenko** [comment]
Hi,
The message definition uses [COMMS_MSG_FIELDS_ACCESS()](https://github.com/arobenko/cc.ublox.generated/blob/master/include/ublox/message/CfgTp5.h#L678) macro which generates access functions to fields `field_X()`. Every field in turn has `value()` member function that returns reference to internal storage.
```
using MyCfgTp5Msg = ublox::message::CfgTp5<...>;
MyCfgTp5Msg msg;
msg.field_tpIdx().value() = ublox::field::CfgTp5TpIdxVal::TIMEPULSE;
```
The [flags](https://github.com/arobenko/cc.ublox.generated/blob/master/include/ublox/message/CfgTp5.h#L572) field is defined to be a bitfield, which uses [COMMS_FIELD_MEMBERS_ACCESS()](https://github.com/arobenko/cc.ublox.generated/blob/master/include/ublox/message/CfgTp5.h#L594) macro. This macro also generates `field_X()` member functions to access appropriate members.
```
msg.field_flags().field_gridUtcGnss().value() = ublox::message::CfgTp5Fields::FlagsMembers::GridUtcGnssVal::GPS;
```
The bits accessible via `field_bits()` member function. The raw value is accessible via `.value()`. The definition of the bits uses [COMMS_BITMASK_BITS_SEQ()](https://github.com/arobenko/cc.ublox.generated/blob/master/include/ublox/message/CfgTp5.h#L437) macro, which generates
`setBitValue_X()` and `getBitValue_X()` for every mentioned bit name.
```
msg.field_flags().field_bits().setBitValue_isFreq(true);
``` 
Some fields, like [freq](https://github.com/arobenko/cc.ublox.generated/blob/master/include/ublox/message/CfgTp5.h#L126) are defined to be optional. The **comms::field::Optional** class just wraps the proper field definition. The latter can be accessed using additional `field()` member function.
```
msg.field_freq().field().value() = 100;
```
Also note, that every _optional_ field has a mode (exists, missing, or tentative). It is possible to manually update the modes of the optional fields.
```
msg.field_freq().setExists();
msg.field_period().setMissing();
```
**HOWEVER** it is not recommended. The message's **refresh** functionality takes a look at the values of the relevant flags and marks such optional fields as existing or missing, just call `doRefresh()` member function.
```
msg.doRefresh();
assert(msg.field_freq().doesExist());
assert(msg.field_period().isMissing());
```

This is quick and short summary of how to access the fields and their values. I strongly recommend to download and read `doc_comms_X` documentation of the [COMMS Library](https://github.com/arobenko/comms_champion#comms-library) from the latest [release artifacts](https://github.com/arobenko/comms_champion/releases) and read [How to Use Defined Custom Protocol](https://github.com/arobenko/comms_champion/blob/master/comms/doc/page_use_prot.dox) page for more detailed guidance on how to define your message interfaces as well as access your fields' values. Seeing API reference of **COMMS** library classes will also be of great help.

Hope it helps.
Regards,
Alex

**Comment by v-prgmr** [comment]
@arobenko , 
````
using MyCfgTp5Msg = ublox::message::CfgTp5<...>; 
````
throws the following error. "parameter pack declaration is not allowed here".

**Comment by arobenko** [comment]
Hi @vishal-prgmr 
When I put `...` in the example code I meant whatever-interface-class-your-application-is-using, not three-dots-verbatim.

I'd like to emphasize again, the ublox library defines UBX protocol using types and classes from the [COMMS Library](https://github.com/arobenko/comms_champion#comms-library). Is is **paramount** to understand how to use the latter. Please download latest [doc_comms_X.zip](https://github.com/arobenko/comms_champion/releases) and spend some time on reading the [How to Use Defined Custom Protocol](https://github.com/arobenko/comms_champion/blob/master/comms/doc/page_use_prot.dox) page. I will also be beneficial if you download and read latest [doc_ublox_X.zip](https://github.com/arobenko/cc.ublox.commsdsl/releases). It adds some extra information on top of [COMMS Library](https://github.com/arobenko/comms_champion#comms-library) documentation. Please don't blindly copy-paste my code snippets, but try to understand what's going on and what I mean. 

In general, there is [ublox::Message](https://github.com/arobenko/cc.ublox.generated/blob/master/include/ublox/Message.h) class that is extendable with various options from the [COMMS Library](https://github.com/arobenko/comms_champion#comms-library). For example the following definition adds polymorphic read functionality to the interface class:
```
using MyInterface = 
    comms::ublox::Message<
        comms::option::app::ReadIterator<const std::uint8_t*> // Adds polymorphic read
    >;
```
The following definition adds also polymorphic write and length calculation.
```
using MyInterface = 
    comms::ublox::Message<
        comms::option::app::ReadIterator<const std::uint8_t*>, // Adds polymorphic read
        comms::option::app::WriteIterator<std::uint8_t*>, // Adds polymorphic write
        comms::option::app::LengthInfoInterface // Adds polymorphic length caclulation
    >;
```
The full blown interface with all the available polymorphic functions will look like this:
```
using MyInterface = 
    comms::ublox::Message<
        comms::option::app::ReadIterator<const std::uint8_t*>, // Adds polymorphic read
        comms::option::app::WriteIterator<std::uint8_t*>, // Adds polymorphic write
        comms::option::app::LengthInfoInterface, // Adds polymorphic length caclulation
        comms::option::app::IdInfoInterface, // Adds polymorphic message ID retrieval
        comms::option::app::ValidCheckInterface, // Adds polymorphic contents validity check
        comms::option::app::RefreshInterface, // Adds polymorphic refreshing (bringing message contents into a consistent state)
        comms::option::app::NameInterface, // Adds polymorphic message name retrieval
        comms::option::app::Handler<MyHandler> // Adds polymorphic dispatch to handler functionality
    >;
```
It is possible not to pass any extension options. In this case the message interface won't have any virtual function(s) and every message definition will be like using a struct.
```
using MyInterface = ublox::Message<>;
```
Choose the common message interface class/type definition applicable to your application, that you are developing. Once it is defined, you can pass it as the first template parameter of any ublox protocol message definition.
```
using MyCfgTp5Msg = ublox::message::CfgTp5<MyInterface>; 
```
Such definition will use template meta-programming magic and will implement every virtual function that was added to your interface class.

Every message definition class also defines multiple **non-virtual** functions with **doX** prefix, which can be used by your application.
```
template <typename TInterface>
class ublox::message::CfgTp5
{
public:
    // Read operation
    template <typename TIter>
    comms::ErrorStatus doRead(TIter& iter, std::size_t len);

    // Write operation
    template <typename TIter>
    comms::ErrorStatus doWrite(TIter& iter, std::size_t len) const;

    // Serialization length calculation
    std::size_t doLength() const;

    // Validity check
    bool doValid() const;

    // Bring message to a consistent state
    bool doRefresh();

    // Get message name
    static const char* doName();
};
```

Regards,
Alex

**Comment by v-prgmr** [comment]
@arobenko , Thank you for the comprehensive replies. I am going through the documentation to see how I should define my message interface.

**Comment by v-prgmr** [comment]
@arobenko , defining the message interface is still confusing. I still didn't get that part right. Referring to the demo example where the message interface class handles reading the data at the serial port and its serialization, in this situation the added polymorphic virtual functions ReadIterator to the InMessage class makes sense. 

However, if I wanted to reverse the polarity using the setBitValue_polarity() method, how do I define the message interface.

**Comment by arobenko** [comment]
The example code splits the messages into [input (InMessage)](https://github.com/arobenko/cc.ublox.commsdsl/blob/master/examples/simple_pos/Session.h#L22) and [output (OutMessage)](https://github.com/arobenko/cc.ublox.commsdsl/blob/master/examples/simple_pos/Session.h#L29) ones and defining separate interfaces for both of them. Nothing prevents you from combining these two interfaces into a single one if you want, and using it for both input and output messages.
```
using MyInterface = 
    ublox::Message<
        comms::option::ReadIterator<const std::uint8_t*>,
        comms::option::WriteIterator<std::uint8_t*>,
        comms::option::LengthInfoInterface,
        /* Any other options you want to pass */
    >;
```

If you want to prepare and send out CFG-TP5 message, do something like code below (assuming you will have separate interface definition for output messages):
```
using MyOutCfgTp5 = ublox::message::CfgTp5<OutMessage>;
MyOutCfgTp5 msg;
auto& flagsField = msg.field_flags(); // access to flags field.
auto& bitsInFlags = flagsField.field_bits(); // Access the "bits" member
bitsInFlags.setBitValue_polarity(true); // Update the polarity value
/* Update all other values, serialize the message and send it over I/O link */
```
The update is possible to be done in a single line:
```
msg.field_flags().field_bits().setBitValue_polarity(true);
```

**Comment by v-prgmr** [comment]
Thank you so much for yet another comprehensive reply. 
The problem is solved. I can set the desired fields and also verify the set values by polling them in the U-centre platform.

**Comment by v-prgmr** [comment]
Greetings @arobenko ,
I have another question. How do i set the value for the bitfields flag "**gridUtcGps**" in the class **CfgTp5** ?

**Comment by arobenko** [comment]
Hi @vishal-prgmr,
It's something like:
```
auto& flagsField = msg.field_flags();
auto& gridUtcGnssField = flagsField.field_gridUtcGnss();
gridUtcGnssField.value() = ... /*Something*/
```
or in one go:
```
msg.field_flags().field_gridUtcGnss().value() = ... /* Something */
```
Now the `Something` depends on the version you are using. In case you updated to the latest release from the last week, then it's going to be:
```
msg.field_flags().field_gridUtcGnss().value() = CfgTp5FieldsCommon::FlagsMembersCommon::GridUtcGnssVal::GPS;
```
If your version is not the latest, then the enum value definition actually resides in `CfgTp5Fields::FlagsMembers`:
```
msg.field_flags().field_gridUtcGnss().value() = 
    CfgTp5Fields</*Put your app options here */>::FlagsMembers::GridUtcGnssVal::GPS;
```
You can use both variants with the latest release.

Hope it helps.

**Comment by v-prgmr** [comment]
Thank You
