### ISSUE TITLE
CfgMsg needs additional Ids for RCTM messages

### ISSUE THREAD

**Issue by mathisloge** [arobenko/cc.ublox.commsdsl#6]
Since UBXv9 there are more msgId especially for the CfgMsg to set RCTM Message Rate. 

[https://www.u-blox.com/sites/default/files/u-blox_ZED-F9P_InterfaceDescription_%28UBX-18010854%29.pdf#page=257&zoom=100,0,124](https://www.u-blox.com/sites/default/files/u-blox_ZED-F9P_InterfaceDescription_%28UBX-18010854%29.pdf#page=257&zoom=100,0,124)

In the coming days, i will be making a pull request to address these changes.

**Comment by mathisloge** [comment]
The pull request will definitely contain CFG-VALSET, CFG-VALGET and CFG-VALDEL. Maybe more.

**Comment by mathisloge** [comment]
@arobenko 

Just one quick question: [https://github.com/mathisloge/cc.ublox.commsdsl/blob/master/dsl/message/CfgValset.xml](https://github.com/mathisloge/cc.ublox.commsdsl/blob/master/dsl/message/CfgValset.xml) 

I have to put the variant inside a seperate `<field/>` tag. otherwise it will throw a build error like 

> `cannot find field referenced by "element" property (cfgData).`


And one design question:  Currently I´m putting all cfg-items inside common-cfg.xml (inside my fork). Bad or good. What are your thoughts on that?

**Comment by arobenko** [comment]
I don't feel comfortable merging any **partial** work of ublox-9 support. Please do the full support on separate branch, before submitting a pull request. Note, that there may be other people (see #4) that might work on it as well.

As for the <list> field, should work as [described](https://github.com/arobenko/CommsDSL-Specification/blob/master/fields/list.md).
```
<list name="cfgDataList">
    <variant name="cfgData">
    </variant>
</list>
```
If it doesn't work, it's a bug in [commsdsl](https://github.com/arobenko/commsdsl) protocol generator.
You may also try to put it in the "element" node like [here](https://github.com/arobenko/cc.demo1.commsdsl/blob/master/dsl/schema.xml#L283).
```
<list name="cfgDataList">
    <element>
        <variant name="cfgData">
        </variant>
    </element>
</list>
```

**Comment by mathisloge** [comment]
Ive noticed the other forks, but they just use a data field for the options, which is not really the optimal case. I will work on the **full** support for ubx9. 

I think it was just a usage fault from me. Ive used it like described [here ](https://github.com/arobenko/CommsDSL-Specification/blob/master/fields/variant.md). 
So that i first set the variant and declared the list afterwards with the element attribute pointing towards the variant, but everything inside the Message object.

**Comment by arobenko** [comment]
Full support of ublox-9 receiver was introduced in the recent [v0.20](https://github.com/commschamp/cc.ublox.commsdsl/releases/tag/v0.20) release.
