### ISSUE TITLE
New message configuration

### ISSUE THREAD

**Issue by carlossanzprieto** [arobenko/cc.ublox.commsdsl#8]
Hi @arobenko , great work.  I´m new at prgramming and i guess i´ll make my way on compiling and obtaining the final exe and allthisstuff
But i need to read UBX-NAV-HPPOSLLH from an ZED f9p , and I´ve read the code, and definign the sentence, and translating it to a normal data, seems inaccesible to my knowledge.
Just to know, Is there eany implementation to poll this ,essage?
Regards

**Comment by arobenko** [comment]
Hi @carlossanzprieto,
I'm not sure I understand your question. There is **NavHpposllhPoll** poll message defined in [dsl](https://github.com/arobenko/cc.ublox.commsdsl/blob/master/dsl/message/NavHpposllh.xml#L19), which ends up being separate **ublox::message::NavHpposllhPoll** message in the [generated code](https://github.com/arobenko/cc.ublox.generated/blob/master/include/ublox/message/NavHpposllhPoll.h#L36). You can serialize and send this message periodically.

There is also an [example](https://github.com/arobenko/cc.ublox.commsdsl/tree/master/examples/simple_pos) application that polls (once a second) for NAV-POSLLH message. The main logic resides in [Session.cpp](https://github.com/arobenko/cc.ublox.commsdsl/blob/master/examples/simple_pos/Session.cpp).
When [handling](https://github.com/arobenko/cc.ublox.commsdsl/blob/master/examples/simple_pos/Session.cpp#L47) incoming "NAV-HPPOSLLH" message you need to combine regular and "hp" values, something like:
```
auto lat = comms::units::getDegrees<double>(msg.field_lat()) + comms::units::getDegrees<double>(msg.field_latHp());
auto lon = comms::units::getDegrees<double>(msg.field_lon()) + comms::units::getDegrees<double>(msg.field_lonHp());
auto heght = comms::units::getMeters<double>(msg.field_height()) + comms::units::getMeters<double>(msg.field_heightHp());
```
Hope it helps.

**Comment by carlossanzprieto** [comment]
Thanks @arobenko 

so in session.cpp I´ll have to include   NavHpposllhPoll.h
in 
void Session::sendPosPoll()

I´ll have to change 
using OutNavPosllhPoll = ublox::message::NavPosllhPoll<OutMessage>;
by
using OutNavPosllhPoll = ublox::message::NavHpposllhPoll<OutMessage>;

Change  polling timer in: 
m_pollTimer.expires_from_now(boost::posix_time::seconds(1));
Substitute 1 by 60 to make it every minute for example

and in  msg.field_LatHP  I´ll have this value

But i don´t get why i have to  combine   regular and "hp" values.
Wouldn´t auto heght = comms::units::getMeters<double>(msg.field_LatHP())   suffice?
Will the prgram print it on screen to check, won´t it?
thanks in advance

**Comment by arobenko** [comment]
To the best of my understanding the "HP" part is an **adjustment** to the regular part to make it "high precision", that's why you need to add it. The printed value of "HP" part is going to be somewhere between the [-0.00000099 - 0.00000099]. If you don't need the "high precision" part, maybe the regular NAV-POSLLH message is good enough for you.

**Comment by carlossanzprieto** [comment]
Ok, thanks, I´ll give it a try.

Regards
