### ISSUE TITLE
Setting Configuration for TimTm2 Message

### ISSUE THREAD

**Issue by v-prgmr** [arobenko/cc.ublox.commsdsl#9]
Greetings,

I am trying to set the configuration for the message UBX-TIME-TM2. I am not able to access some of the bitsflag.

````
using TimeMarkOut = ublox::message::TimTm2<OutMessage>;

TimeMarkOut msg2;
msg2.field_flags().field_bitsHigh().setBitValue_newRisingEdge(true);
msg2.field_flags().field_bitsLow().setBitValue_mode(true);
msg2.field_flags().field_bitsLow().setBitValue_run(false);
sendMessage(msg2);
````

I cannot set the bits for the fields - timeBase, UTC, time. How do I set these flags? 
Thank You

**Comment by v-prgmr** [comment]
I got this working. Thank You. :)

**Comment by v-prgmr** [comment]
Greetings @arobenko ,
Setting up the configuration is as I have mentioned in the previous comment. 

But how should i enable the message? 
Thank You

**Comment by arobenko** [comment]
Sorry @vishal-prgmr, I don't understand what you are asking. I haven't worked with ublox protocol for a while and don't remember much. I can help you with how to use my work, but to understand what messages to send to the ublox receiver please refer to official documentation or ask on u-blox dedicated forums.

**Comment by v-prgmr** [comment]
@arobenko Thank you :)
